volumes:
  jenkins:
    name: jenkins

networks:
  jenkins:
    name: jenkins
    driver: bridge

services:
  jenkins:
    image: jenkins
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    restart: always
    env_file:
      - .env
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins:/var/jenkins_home
    networks:
      - jenkins